### ISSUE TITLE
Add Logo to side of Whisker Menu

### ISSUE THREAD

**Issue by grassmunk** [grassmunk/Chicago95#111]
So after reading https://github.com/grassmunk/Chicago95/issues/110 i wanted to try and add the 'Windows 95' to whisker menu. I've made an SVG and generated the following files:
![menu_side-chicago](https://user-images.githubusercontent.com/3452173/77482787-f7c35980-6de3-11ea-814f-45f1a34e8608.png)
![menu_side-windows](https://user-images.githubusercontent.com/3452173/77482789-f85bf000-6de3-11ea-93fe-820515ac7271.png)

and I'm able to use them in Redmond97 and i think it looks pretty boss and close to the original:

![image](https://user-images.githubusercontent.com/3452173/77483009-67394900-6de4-11ea-9bd3-a31aba7d23ae.png)

 but i cant get them to work in Chicago95. @EMH-Mark-I do you know what values i need to change in whiskermenu.css to make it work?

I figure we can make it optional for people they can either use the current png, or if its stretched/squashed they can use the SVG to make their own.

**Comment by EMH-Mark-I** [comment]
Sure, I'll look back into it and report.

**Comment by grassmunk** [comment]
Awesome! Thank you. The file that has the code to do this is `whisker-menu.css` and the specific code is on line 60:

```css
#whiskermenu-window stack:first-child > scrolledwindow {
  border: none;
  box-shadow: none;
  padding: 1px;
  padding-left: 2px;
  margin-left: 1px;
  margin-bottom: 1px;
  margin-right: 0px;
  border-radius: 0px;
  background-color: @button_bg_color;
  border-image: url("assets/menu_side.png");
  border-image-slice: 0 0 0 30;
  border-left: 25px solid; }
```
