### ISSUE TITLE
Theme not Applying to GTK-4 applications

### ISSUE THREAD

**Issue by 266-750Balloons** [grassmunk/Chicago95#256]
I use XFCE4, but there are two applications I use that transitioned to GTK4 (gHex and gnome-clocks) that have transitioned to GTK 4 and ever since, they have used the Adwaita theme, but with the correct fonts and icons. They used to theme correctly under GTK3. I am assuming this is due to a lack of GTK4 support by Chicago95. Here's an image of the problem:
![image](https://user-images.githubusercontent.com/79549730/181392448-5b59c3fe-e77a-4217-8615-06d3898f28ed.png)
- - -
Distribution: Debian Bookworm
Desktop: XFCE 4.16
Architecture: AMD64
Kernel: 5.18.0-14.2-liquorix-amd64 and several previous normal (non-liquorix) Debian kernels

**Comment by EMH-Mark-I** [comment]
Currently the Chicago95 GTK theme only supports up to GTK3. I don't think it will work well with GTK4 due to many features being removed.

**Comment by 266-750Balloons** [comment]
![image](https://user-images.githubusercontent.com/79549730/199382527-4a0d3a6c-0516-4a99-861a-bcfd6aa4997a.png)
I've decided to go Janeway and try to create a gtk4 theme. Better something than nothing. Here is a screenshot prototype (missing a lot). The only issue so far is I am having trouble changing window button sizes (the gtk3 method doesn't work).

This is my gtk.css so far:
```css
button {
	background-color: #C0C0C0;
	border-style: inset;
	border-width: 1px;
	border-color: white black black white;
	padding: 0;
}
button:active {
	border-color: black;
}
window {
	background-color: #C0C0C0;
	border-style: inset;
	border-width: 1px;
	border-color: white black black white;
color: black;
}
headerbar {
	background-color: #000080;
	padding: 2px;
}
```
I might make a pull request when I am more ready.
